---
apiVersion: v1
kind: Pod
metadata:
  name: secret-hook
spec:
  containers:
  - name: shell-operator
    image: ttacrroodsefvnkxhc.azurecr.io/kaiku-secret-wacher:latest
    imagePullPolicy: Always
  serviceAccountName: secret-watcher-acc
  imagePullSecrets:
  - name: test