---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-watcher-acc

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: secret-watcher
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: secret-watcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-watcher-role
subjects:
  - kind: ServiceAccount
    name: secret-watcher-acc
    namespace: secret-watcher